# STOA Platform - staging Environment
environment: staging
domain: staging.stoa.cab-i.com
namespace: stoa-system

gateway:
  replicas: 1
  
keycloak:
  realm: stoa
  
vault:
  path: secret/stoa/staging
