# CAB-279: Demo Tenants Kustomization
# Purpose: Deploy demo tenants and subscriptions for STOA MVP
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: demo-tenants
  annotations:
    stoa.cab-i.com/created-by: cab-279

namespace: stoa-system

# Labels applied to all resources
commonLabels:
  stoa.cab-i.com/demo: "true"
  stoa.cab-i.com/environment: demo

# Resources to deploy
resources:
  - team-alpha.yaml
  - team-beta.yaml
  - subscriptions.yaml
