apiVersion: v1
kind: Service
metadata:
  name: control-plane-ui
  namespace: stoa-system
  labels:
    app: control-plane-ui
    app.kubernetes.io/name: control-plane-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: control-plane-ui
