{{- if .Values.kafkaBridge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stoa-platform.fullname" . }}-kafka-bridge
  labels:
    {{- include "stoa-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-bridge
spec:
  type: {{ .Values.kafkaBridge.service.type }}
  ports:
    - port: {{ .Values.kafkaBridge.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stoa-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-bridge
{{- end }}
