apiVersion: v2
name: stoa-platform
description: STOA Platform - AI-Native API Management
type: application
version: 0.2.0
appVersion: "0.2.0"
maintainers:
  - name: CAB Ing√©nierie
    email: support@cab-i.com
