apiVersion: v2
name: stoa-platform
description: STOA Platform - Multi-tenant API Management Platform
type: application
version: 0.1.0
appVersion: "2.0.0"

keywords:
  - api-management
  - multi-tenant
  - mcp-gateway
  - gitops

maintainers:
  - name: CAB Ingenierie
    email: platform@cab-i.com

dependencies: []
