apiVersion: v2
name: stoa-platform
description: STOA Platform - Multi-tenant API Management with GitOps integration
type: application
version: 2.0.0
appVersion: "2.0.0"

keywords:
  - api-management
  - gitops
  - multi-tenant
  - observability

home: https://stoa.cab-i.com
sources:
  - https://gitlab.com/cab6961310/stoa-gitops

maintainers:
  - name: CAB Ingenierie
    email: admin@cab-i.com

annotations:
  category: Infrastructure
