---
# Handlers for webMethods role

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart webmethods
  systemd:
    name: webmethods
    state: restarted

- name: restart cloudwatch-agent
  systemd:
    name: amazon-cloudwatch-agent
    state: restarted
